### ISSUE TITLE
Create a calculator using HTML/CSS/JS

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Development#1]
Any number of people can work in a single issue,
This issue is open for all.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by bhakti0302** [comment]
Can I work on this?

**Comment by G1Joshi** [comment]
Sure @bhakti0302 go for it,
All the best.

**Comment by satwik-chowdary** [comment]
I would like to do this

**Comment by arnoob16** [comment]
@G1Joshi can more than one person work on a issue?

**Comment by aniketsingh98571** [comment]
I would Like to work on it. @G1Joshi

**Comment by hrtywhy** [comment]
i have calculator in c++
can  i PR?

**Comment by prachi0513** [comment]
can I submit my first PR for hacktoberfest here!

**Comment by Nightsmore** [comment]
Hey, I'd like to work on this!

**Comment by cosmoimai** [comment]
sir, I have completed the calculator #124

**Comment by minhaj-313** [comment]
Hi, I am Interested to Create a Calculator By Using HTML CSS JS. For Hactoberfest

**Comment by minhaj-313** [comment]
I did Created please Merge My PR - Hacktoberfest-Accepted
