### ISSUE TITLE
UTM Builder

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Development#134]
## Create a UTM builder having parameters utm_source, utm_medium, utm_campaign.

Any number of people can work in a single issue,
This issue is open for all.

**Comment by DanB288** [comment]
Hey @G1Joshi !!, I would like to work on this issue😉. Should I include tests as well ?

**Comment by scampiuk** [comment]
Hey @G1Joshi , opened a PR for the #hacktoberfest challenge, something simple, many thanks 🙇‍♂️
