### ISSUE TITLE
Random Number Generator

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Development#18]
Any number of people can work in a single issue,
This issue is open for all.

**Comment by hpnightowl** [comment]
can i take this issue and build it in python?

**Comment by prikshitsetia** [comment]
may I work on this issue?

**Comment by divyavit** [comment]
Hi, I am interested in working on this issue, can you please elaborate on what has to be done exactly

**Comment by veldakarimi** [comment]
I have worked on a simple solution to this using python at #46

**Comment by jnvee** [comment]
I want to work on this

**Comment by veldakarimi** [comment]
I have worked on a simple solution to this using python at #46

**Comment by VectorXz** [comment]
I've done by using html/js at #116

**Comment by cosmoimai** [comment]
the task is done sir, #126

**Comment by Wavist** [comment]
I just sent in a PR
