### ISSUE TITLE
Number Guessing Game

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Development#19]
## Build a number guessing game.

Any number of people can work in a single issue,
This issue is open for all.

**Comment by BilliamsFluster** [comment]
Am I able to participate in c++?

**Comment by veldakarimi** [comment]
I have added a number guessing game using python at #50

**Comment by ParthSaini-2006** [comment]
#109

**Comment by veldakarimi** [comment]
I have added a number guessing game using python at #50
