### ISSUE TITLE
Create a calendar using HTML/CSS/JS

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Development#2]
Any number of people can work in a single issue,
This issue is open for all.
### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by bhakti0302** [comment]
Can I work on this issue @G1Joshi

**Comment by G1Joshi** [comment]
Sure @bhakti0302 go for it,
All the best.

**Comment by satwik-chowdary** [comment]
Hey, I want to do this

**Comment by sandiproybalitha** [comment]
I want to contribute
