### ISSUE TITLE
Tic-Tac-Toe Game

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Development#21]
## Build a tic-tac-toe game.

Any number of people can work in a single issue,
This issue is open for all.

**Comment by dramikei** [comment]
Can this be done in In any language?

**Comment by AndreiG23** [comment]
I would like to add my SFML Tic Tac Toe made in c++

**Comment by KeerthanaHK** [comment]
Hi, Can I add Tic-Tac-Toe game done using Python? @G1Joshi

**Comment by prikshitsetia** [comment]
hey, I would like to add my GUI based game in java

**Comment by divyanshusahu** [comment]
I will add my HTML/JS Tic-Tac-Toe

**Comment by jaideepghosh** [comment]
Hey @G1Joshi 
Added a tictoctoe game in react. Have a look on the PR id [49](https://github.com/C0D1NG/Development/pull/49)

**Comment by veldakarimi** [comment]
@G1Joshi I submitted a solution of Tic Tac Toe using Python, it's at #52

**Comment by kshitij5** [comment]
Added a solution to TicTacToe using Java! #108

**Comment by veldakarimi** [comment]
@G1Joshi I submitted a solution of Tic Tac Toe using Python, it's at #52
