### ISSUE TITLE
Countdown Clock and Timer

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Development#22]
## Build a countdown clock and timer.

Any number of people can work in a single issue,
This issue is open for all.

**Comment by Mishrasubha** [comment]
Hey, can I do this in python?

**Comment by shreyaa-sharmaa** [comment]
I can make a PR for countdown clock and timer in JS.

**Comment by burnerlee** [comment]
i can make a PR for countdown clock and timer in golang

**Comment by STM3900** [comment]
'Working for an JS/HTML/CSS version !

**Comment by RizalMadani** [comment]
I would like to try this

**Comment by thinkswell** [comment]
@G1Joshi , Hello, I have done some of code optimisation and have done small changed to the UI to my previous version of Countdown Clock and Timer, Can you please review my PR #105
