### ISSUE TITLE
World Clock using Flutter

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Development#25]
## Build a world clock using flutter framework.

Any number of people can work in a single issue,
This issue is open for all.

**Comment by nayakastha** [comment]
I am interested to work on this issue.

**Comment by arnoob16** [comment]
Can you elaborate a bit? Like what should the app do?

**Comment by HarishGuragol** [comment]
I am interested to collaborate to it

**Comment by nayakastha** [comment]
Something like one enters the city name and get the local time. Basically, it will be a one screen app

**Comment by kshitij5** [comment]
I am interested in this issue! Please assign it to me!

**Comment by shwhite17** [comment]
I am interested in this issue, can @G1Joshi you assign to me ? please
