### ISSUE TITLE
Create a to-do list using HTML/CSS/JS

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Development#3]
Any number of people can work in a single issue,
This issue is open for all.

**Comment by rafaeldfigueiredo** [comment]
Sorry if Git issue isn't the best place to ask questions, I'm quite new to the platform. Is this a repo to people to gather and work together?

**Comment by G1Joshi** [comment]
Yes @rafaeldfigueiredo this is a public repo and anyone can collaborate on this project.

**Comment by shreyaa-sharmaa** [comment]
I can take it up if that's okay?
